# Taps
tap "homebrew/cask-versions"

# Desktop Apps
cask "1password"
cask "appcleaner"
cask "arduino-ide"
cask "authy"
cask "clipy"
cask "daisydisk"
cask "gutenprint"
cask "imageoptim"
cask "keybase"
cask "numi"
cask "openscad"
cask "orbstack"
cask "spotify"
cask "the-unarchiver"
