# Taps
tap homebrew/cask-versions

# Desktop Apps
cask '1password'
cask 'authy'
cask 'clickup'
cask 'clipy'
cask 'daisydisk'
cask 'figma'
cask 'firefox-nightly'
cask 'google-chrome'
cask 'grammarly'
cask 'imageoptim'
cask 'keybase'
cask 'local'
cask 'numi'
cask 'protonvpn'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'the-unarchiver'
cask 'virtualbox'
cask 'webtorrent'
