# Taps
tap homebrew/cask-versions

# Desktop Apps
cask 'amethyst'
cask '1password'
cask 'appcleaner'
cask 'arc'
cask 'arduino-ide'
cask 'authy'
cask 'clickup'
cask 'clipy'
cask 'daisydisk'
cask 'gutenprint'
cask 'imageoptim'
cask 'keybase'
cask 'nordvpn'
cask 'numi'
cask 'openscad'
cask 'orbstack'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
