version: '3.7'

services:
  db:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    container_name: web
    build: .
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
        - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
