version: '3'

services:
  db:
    container_name: db
    image: postgres:10-alpine

  web:
    container_name: web
    build: .
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
